name: Setup Zabbix Instance

on: push

jobs:
  zabbix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        zabbix-version: ['5.2', '5.0', '4.0', '3.0']

    steps:
      - name: Checkout repo kumari-priya/github-actions
        uses: actions/checkout@v2

      - name: Checkout repo zabbix/zabbix-docker
        uses: actions/checkout@v2
        with:
          repository: zabbix/zabbix-docker
          ref: ${{ matrix.zabbix-version }}
          path: ./zabbix-docker

      - name: Build Zabbix Containers
        run: |
          docker --version
          docker-compose --version
          ls -la
          docker-compose -f ./zabbix-docker/docker-compose_v3_alpine_pgsql_latest.yaml up -d
          sleep 10
          docker-compose -f ./zabbix-docker/docker-compose_v3_alpine_pgsql_latest.yaml ps
