name: Setup Zabbix Instance
on: push
jobs:
  zabbix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: zabbix/zabbix-docker
          ref: 5.2
          path: ./zabbix-docker
      - run: |
          docker --version
          docker-compose --version
          docker-compose -f ./zabbix-docker/docker-compose_v3_alpine_pgsql_latest.yaml up
          docker-compose -f ./zabbix-docker/docker-compose_v3_alpine_pgsql_latest.yaml ps
